spring.application.name=jeky-backend

spring.datasource.url=jdbc:mysql://localhost:3306/db_jeky
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
jwt.secret=jeky-admin-secret-key-minimal-32-character-long
jwt.expiration-ms=86400000
